[project]
name = "layout-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "plotly",
]

[project.optional-dependencies]
dev = ["pytest"]
